FROM ubuntu:24.04

# -- packages --------------------------------------------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates software-properties-common curl \
    clang clang-format cmake ninja-build libstdc++-12-dev jq git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# -- add toolchain repository ---------------------------------------------
RUN add-apt-repository -y ppa:ubuntu-toolchain-r/test \
    && apt-get update \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# -- noirup and bbup -------------------------------------------------------
RUN /bin/bash -c "curl -L https://raw.githubusercontent.com/noir-lang/noirup/refs/heads/main/install | bash \
    && source ~/.bashrc \
    && ~/.nargo/bin/noirup"

ENV PATH="/root/.nargo/bin:$PATH"

RUN /bin/bash -c "curl -L https://raw.githubusercontent.com/AztecProtocol/aztec-packages/refs/heads/master/barretenberg/bbup/install | bash \
    && source ~/.bashrc \
    && ~/.bb/bbup"

ENV PATH="/root/.bb:$PATH"

VOLUME ["/circuits"]
VOLUME ["/test"]

# RUN noirup

# RUN bbup --version 0.87.2
