[package]
name = "greco"
version = "0.1.0"
type = "lib"
entry = "circuits/lib.nr"
authors = ["Gnosis Guild / Enclave"]
license = "MIT"

[dependencies]
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }