name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - noir

jobs:
  rust:
    name: Rust CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: crates
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust 1.85.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.85.0
          components: rustfmt
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: crates -> target

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run tests
        run: cargo test

      - name: Build
        run: cargo build --release

  noir:
    name: Noir CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: circuits
    steps:
      - uses: actions/checkout@v4

      - name: Install Nargo
        uses: noir-lang/noirup@v0.1.3
        with:
          toolchain: stable

      - name: Check Noir formatting
        run: nargo fmt --check

      - name: Build Noir project
        run: nargo check

      - name: Run Noir tests
        run: nargo test
