name: Circuit Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-circuit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nargo
      uses: noir-lang/noirup@v0.1.3
      with:
        toolchain: latest

    - name: Install Barretenberg
      run: |
        # Download and install Barretenberg CLI
        curl -L https://github.com/AztecProtocol/aztec-packages/releases/download/aztec-packages-v0.41.0/barretenberg-x86_64-linux-gnu.tar.gz | tar -xz
        sudo mv bb /usr/local/bin/
        chmod +x /usr/local/bin/bb

    - name: Compile circuit
      working-directory: ./test
      run: nargo compile

    - name: Execute circuit
      working-directory: ./test
      run: nargo execute

    - name: Generate proof
      working-directory: ./test
      run: bb prove -b ./target/test.json -w ./target/test.gz -o ./target

    - name: Write verification key
      working-directory: ./test
      run: bb write_vk -b ./target/test.json -o ./target

    - name: Verify proof
      working-directory: ./test
      run: bb verify -k ./target/vk -p ./target/proof

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: circuit-artifacts
        path: |
          test/target/test.json
          test/target/test.gz
          test/target/proof
          test/target/vk
          test/target/public_inputs
