name: Circuit Test

on: [push, pull_request]

jobs:
  test-circuit:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nargo
        run: |
          curl -L https://raw.githubusercontent.com/noir-lang/noirup/refs/heads/main/install | bash
          source ~/.bashrc
          ~/.nargo/bin/noirup

      - name: Add Nargo to PATH
        run: |
          echo "$HOME/.nargo/bin" >> $GITHUB_PATH

      - name: Install Barretenberg
        run: |
          # Download and install Barretenberg CLI
          curl -L https://raw.githubusercontent.com/AztecProtocol/aztec-packages/refs/heads/master/barretenberg/bbup/install | bash
          source ~/.bashrc
          ~/.bb/bbup

      - name: Add bb to PATH
        run: |
          echo "$HOME/.bb" >> $GITHUB_PATH

      - name: Compile circuit
        working-directory: ./test
        run: nargo compile

      - name: Execute circuit
        working-directory: ./test
        run: nargo execute

      - name: Generate proof
        working-directory: ./test
        run: bb prove -b ./target/test.json -w ./target/test.gz -o ./target

      - name: Write verification key
        working-directory: ./test
        run: bb write_vk -b ./target/test.json -o ./target

      - name: Verify proof
        working-directory: ./test
        run: bb verify -k ./target/vk -p ./target/proof
